apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # echo -n "supersecret" | base64
  DB_PASSWORD: c3VwZXJzZWNyZXQ=
  # echo -n "my-api-key-12345" | base64
  API_KEY: bXktYXBpLWtleS0xMjM0NQ==
